POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "dfse",
    "number": "12-23323"
}
###
GET http://localhost:3001/api/persons
###
DELETE http://localhost:3001/api/persons/2



###
POST  http://localhost:3001/api/persons/66a6fc0f2bb6e79c7c634864
content-type: application/json

{
    "name": "dfse",
    "number": "4e4ea"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
    
    "number": "1"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
    
    "name": "dedfe"
}

###
GET http://localhost:3001/api/persons/435
