POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "dfse",
    "number": "dedfe"
}
###
GET http://localhost:3001/api/persons
###
DELETE http://localhost:3001/api/persons/2



###
PUT http://localhost:3001/api/persons/66a6fc0f2bb6e79c7c634864
content-type: application/json

{
    "name": "dfse",
    "number": 12345447
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
    
    "number": "dedfe"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
    
    "name": "dedfe"
}